// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ConstantsTest
{

/// Game configuration constants
public static class GameConfig
{
  /// Maximum number of players allowed in a game
  public const int max_players = 100;
  /// Default player health
  public const float default_health = 100.0f;
  /// Maximum inventory slots
  public const ushort max_inventory_slots = 64;
  /// Enable debug mode by default
  public const bool debug_enabled = false;
  /// Tick rate in milliseconds
  public const long tick_rate_ms = 16L;
}


}
