// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ConstantsTest
{

/// Network configuration constants
public static class NetworkConfig
{
  /// Connection timeout in milliseconds
  public const long timeout_ms = 30000L;
  /// Maximum concurrent connections
  public const uint max_connections = 1000;
  /// Default port number
  public const ushort default_port = 8080;
  /// Enable compression
  public const bool compression_enabled = true;
}


}
