// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ConstantsTest
{

/// Physics constants
public static class PhysicsConstants
{
  /// Gravity acceleration (m/s^2)
  public const float gravity = 9.81f;
  /// Maximum velocity
  public const double max_velocity = 299792458.0;
  /// Friction coefficient
  public const float friction = 0.3f;
}


}
